# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 37a79ada-capi-aws
  namespace: 37a79ada
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 37a79ada-capi-aws
subjects:
- kind: ServiceAccount
  name: 37a79ada-capi-aws
